### ISSUE TITLE
create alpheios icons as transparent pdfs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/safari-app-back#1]
The source art for the Alpheios icons can be found in https://github.com/alpheios-project/design-guidelines/tree/master/v1/Alpheios_Logo_SourceArt

The icons are in a photoshop file, alpheios_icon_sizing.psd

@irina060981 do you have any experience with Adobe Illustrator/Photoshop? I tried to get a transparent PDF produced today, but I think there are problems with the layers.

[Asset 1.pdf](https://github.com/alpheios-project/safari-app-back/files/2443295/Asset.1.pdf)

**Comment by irina060981** [comment]
Hello, @balmas !
I am sorry I wasn't able to check this issue yesterday - I dug into inflection games and forgot to check it.
Today I tried to check the pull request and to see how icon looks like now, but I have got such an error in XCode:

<img width="1123" alt="screen shot 2018-10-05 at 16 59 47" src="https://user-images.githubusercontent.com/12377640/46520771-84ace700-c8c0-11e8-9526-80d3c2602b79.png">

It seems to me that we are using different versions of Swift and they are hardly compatible.
I will try to repeat your changes in my source files to see what is happing with icon.

**Comment by irina060981** [comment]
I was able to recreate - https://github.com/alpheios-project/safari-app-back/pull/3

<img width="1248" alt="screen shot 2018-10-05 at 17 34 17" src="https://user-images.githubusercontent.com/12377640/46522291-b6747c80-c8c5-11e8-8e5c-5cc276c3dea2.png">

I think, Bridget, your design skills are quite well! I didn't guess to use badge for changing state :)

**Comment by irina060981** [comment]
merged and closed
