### ISSUE TITLE
Best practices of developing in XCode

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/safari-app-back#4]
I think it would be great to gather and share here best practices for developing with XCode.

XCode stores many build related settings in its proprietary IDE files. Because of this, we have to store at least some XCode config files in version control. However, some of those config setting, usually related to user-specific environment (file open history, for example), can and should be ignored.

We should also not store build results in version control too. Those file are large. They are binary, and analyzing their revision history would bring close to nothing. Multiple revisions of such files stored can lead to performance degradation in Git. And, when needed, those files can easily be recreated by running a build process. 

We could probably start form a `.gitignore` file created by https://www.gitignore.io/

It is also important to always use file paths relative to groups instead of absolute ones when adding a new file to the project. This way file paths will be relative to the project root. It will work no matter where a project directory will be placed.

As a platform target we can probably use MacOS 10.13 (should we go with a lower version to support users with not so up to date platforms?), XCode 10 and Swift 4.2.

Please let me know what do you think

**Comment by balmas** [comment]
this all sounds good to me.

**Comment by kirlat** [comment]
@irina060981, @balmas!
Can you, when you will have time, check if the latest commit for https://github.com/alpheios-project/safari-app-back/tree/safari-app-back-best-practices will work on your machines without any modifications?
I've tried to include best practices into this branch. It has all paths as relative and all unnecessary files removed. It also has an updated `.gitignore`. Build targets are set for Swift 4.2.
Please let me know what do you think. If it will work well for you, I can issue a PR. Thanks!

**Comment by irina060981** [comment]
@kirlat, I am so happy, that you have started from correcting these tricky issues :) I have uploaded your branch, build and test - everything is working well!

**Comment by balmas** [comment]
I was able to build successfully as well. Thanks!

**Comment by kirlat** [comment]
Great, I will issue a PR then
